### ISSUE TITLE
Cursor corruption on AMD

### ISSUE THREAD

**Issue by sodiboo** [Smithay/smithay#1262]
I've tried Smithay-based compositors with two systems, first with an RTX 2060 and then with an RX 7800 XT. The AMD-based GPU has a cursor corruption issue that the NVIDIA-based one doesn't.

The NVIDIA GPU is of note only because the cursor was working fine (though it was not working flawlessly); all attached images and descriptions of the problem are with the RX 7800 XT.

Most often, it is a square of noise, mostly white/gray but with a few colorful pixels.

![image](https://github.com/Smithay/smithay/assets/37938646/40609549-f5e1-4ff1-a85a-ec86c7360301)

Sometimes on startup, it is more of a blocky mess with mostly red/green bars and lots of transparency.

![image](https://github.com/Smithay/smithay/assets/37938646/d6e1614c-a530-44d4-9326-376c120c4dac)

These are pictures with my phone because screenshots do not capture the rendering issue, here is how it looks when i take a screenshot using `niri`'s built-in `screenshot;` command.

![image](https://github.com/Smithay/smithay/assets/37938646/078945ac-5e7c-4837-b525-0fb9423b59a0)

It is *possible* for this corruption to get "better" after a while of running, because it did that once. By this, i mean that the default state of the cursor was restored with some slight artifacts and the other states were still equally corrupted.

---

I experienced this first in `niri` but have narrowed it down to a Smithay issue, given that it does not affect any other compositors i've tried (GNOME, Hyprland, Sway) except for `anvil`.

The lovely people in the smithay matrix channel helped me try some workarounds: `ANVIL_DISABLE_DRM_COMPOSITOR=1` fixes the issue on `anvil` and for `niri`, instructions equivalent to the following patch were provided:

```diff
diff --git a/src/backend/tty.rs b/src/backend/tty.rs
index 01a5305..d1d3d74 100644
--- a/src/backend/tty.rs
+++ b/src/backend/tty.rs
@@ -594,7 +594,7 @@ impl Tty {
             SUPPORTED_COLOR_FORMATS,
             render_formats.clone(),
             device.drm.cursor_size(),
-            Some(device.gbm.clone()),
+            None,
         )?;
 
         let dmabuf_feedback = DmabufFeedbackBuilder::new(device.id, texture_formats.clone())
```

Compiling `niri` with the above patch prevents the issue from occurring.

**Comment by Drakulix** [comment]
Linking https://github.com/Smithay/smithay/pull/1239 as a potential fix.

**Comment by cmeissl** [comment]
@sodiboo Can you verify that this issue is fixed on current master?

**Comment by sodiboo** [comment]
using latest niri commit (after disabling mitigation in the relevant config)

`git pull; cargo run` -> cursor corruption still occurs

`cargo update; cargo run` -> cursor corruption no longer occurs

can confirm, the issue is fixed!

**Comment by cmeissl** [comment]
Thanks!
