### ISSUE TITLE
Winit backend window resize

### ISSUE THREAD

**Issue by csnewman** [Smithay/smithay#148]
With the winit backend, resizing the window has some weird behaviour. The horizontal size updates correctly, however the vertical size appears to just jump to the full display height.

Disabling the following line seems to fix it for me:
https://github.com/Smithay/smithay/blob/0b2e4b42db49736f6516ca9dcb7a127cc4815b2d/src/backend/winit.rs#L704

Not sure where the issue lies, with winit, or whether the window shouldn't be resized during a resize event?

Running on GNOME Shell 3.32.2, on X11. Reproduced with anvil.

**Comment by vberger** [comment]
This is potentially related to the fact that we are a few versions behind on winit, so it may possibly be a winit bug that has been fixed since.

**Comment by csnewman** [comment]
Updating to winit 0.19.5 seemed to make the problem worse, with the resize event constantly being triggered after a resize: (the height is also still wrong.)

```
Dec 23 19:10:38.202 INFO Resizing window to LogicalSize { width: 1280.0, height: 819.0 }, smithay_winit_component: input, smithay_module: backend_winit
Dec 23 19:10:38.202 INFO Resizing window to LogicalSize { width: 1280.0, height: 1004.0 }, smithay_winit_component: input, smithay_module: backend_winit
Dec 23 19:10:38.218 INFO Resizing window to LogicalSize { width: 1280.0, height: 819.0 }, smithay_winit_component: input, smithay_module: backend_winit
Dec 23 19:10:38.219 INFO Resizing window to LogicalSize { width: 1280.0, height: 1004.0 }, smithay_winit_component: input, smithay_module: backend_winit
....
```

Until the program crashes.

**Comment by vberger** [comment]
Hmm, indeed. It looks like this line is a leftover from a previous time, when the winit semantics where different.

While it does nothing problematic on Wayland, it is not needed either. So if it poses problems on x11 I guess we can remove this.

**Comment by vberger** [comment]
This was removed in #172, so I'm going to close this for now. Feel free to reopen if you hit this again from `master`.
