### ISSUE TITLE
Anvil: impossibility to move mouse or use keyboard.

### ISSUE THREAD

**Issue by rvlander** [Smithay/smithay#168]
System :
* Archlinux
* tty1 on gdm
* tty2 on sway

First case:
* switch to tty3 using `Ctrl` + `Alt` + `F3`
* `cd anvil`
* `cargo run -- --tty-dev`
* blocked (anvil bg + anvil cursor)

Second case:
* switch to tty3 using `Ctrl` + `Alt` + `F3`
* `cd anvil`
* `cargo run --features "winit egl udev logind" -- --tty-dev`
* can move mouse and type keyboard
* switch to tty2
* can use sway
* switch to tty3
* blocked (sway bg + anvil cursor) 

In each case the only option is to reboot using power button.

**Comment by Drakulix** [comment]
The first one is likely a permission problem. Because "logind" is normally not compiled in, it will fallback to direct tty acquisition, which requires root permissions on most systems. This sometimes works anyway, if nothing else is running, but libinput might not optain the permissions to open any input devices, leaving you without a way to interact with anvil.

The second one uses logind, but somehow seems to fail to re-acquire the input devices. Can you post a log of it? (Run `cargo run -- --tty-udev > run.log & sleep 30; exit`, which will give you 30 seconds to switch to sway and back before killing anvil.)

You can also setup [Magic SysRq](https://en.wikipedia.org/wiki/Magic_SysRq_key) before to get out of an unresponsive anvi.

**Comment by rvlander** [comment]
I had to setup a, ssh connection to be able to kill it.
Find the log attached. Something bad seems to be happening.
[run3.log](https://github.com/Smithay/smithay/files/4397591/run3.log)

**Comment by vberger** [comment]
I can reproduce this on my system as well. The Magic SysRq can still kill anvil, but it leaves the TTY in an unusable state that I did not manage to fix using other SysRq. Had to reboot.

Indeed, it looks like we have some issue with the management of the rendering context:

```
ar 28 18:49:48.754 INFO Trying to switch to vt 4
Mar 28 18:49:48.764 ERRO Error during rendering: ContextLost
Mar 28 18:49:48.765 ERRO Error during rendering: ContextLost
.........
Mar 28 18:49:52.713 DEBG Reactivating device (226,0), vt: None, seat: seat0, id: 2, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Mar 28 18:49:52.714 INFO Replacing fd, smithay_module: backend_drm
Mar 28 18:49:52.714 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
Mar 28 18:49:52.714 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
Mar 28 18:49:52.810 DEBG Reactivating device (226,1), vt: None, seat: seat0, id: 2, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Mar 28 18:49:52.810 INFO Replacing fd, smithay_module: backend_drm
Mar 28 18:49:52.810 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
Mar 28 18:49:52.810 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
```

**Comment by vberger** [comment]
Actually, these messages are probably something else. An animated client (terminal running cmatrix) keeps running its animation even though keyboard and mouse are unresponsive. So this is something else.

**Comment by vberger** [comment]
Better yet, the display sometimes actually freeze. Looks like we have a race.

I suspect there are two things going on:

- somehow, the input is not properly resumed when coming back from the tty switch
- sometimes, it appears anvil tries to do a page flip after requesting a tty switch, but before processing the suspend events from logind, and this messes up the graphics state.

Btw, I can reliably run anvil and keep it from freezing my computer with this command:

```
./target/debug/anvil --tty-udev 2> out.log&; sleep 30; pkill anvil
```

So anvil still answers to a regular kill (not a `-9`), meaning it is not completely frozen.

**Comment by vberger** [comment]
Okay, I've got the issue for the "input" part.

For some reason, logind floods us with "done"-type "PauseDevice" events relating to input. Every time we receive a `PauseDevice` event relating to input, we suspend libinput. This flood causes us to re-pause libinput just after having resumed it when coming back from tty switch.

I tried the dirty hack of ignoring all "gone" events, and it does solve the input freeze issue. The graphics still crash, but at least anvil now responds to keyboard controls to quit it.

I'll investigate to see what would be the proper thing to do. I suspect these "gone" events are actually destinated to libinput itself and ignoring them is the correct choice, but I'm not completely sure of the proper way to filter them out.

**Comment by csnewman** [comment]
Further log (with dbg lines):
```
Apr 12 12:56:32.775 INFO Trying to switch to vt 2
[src/backend/drm/legacy/surface.rs:243] x = PermissionDenied
Apr 12 12:56:32.776 ERRO Error during rendering: ContextLost
Apr 12 12:56:32.777 DEBG Request of type "gone" to close device (13,86), vt: None, seat: seat0, id: 20, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Apr 12 12:56:33.304 DEBG Request of type "force" to close device (13,73), vt: None, seat: seat0, id: 20, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
....
Apr 12 12:56:33.312 DEBG Request of type "gone" to close device (13,73), vt: None, seat: seat0, id: 20, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Apr 12 12:56:38.994 DEBG Reactivating device (226,0), vt: None, seat: seat0, id: 20, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Apr 12 12:56:38.995 INFO Replacing fd, smithay_module: backend_drm
[src/backend/drm/legacy/surface.rs:243] x = Unknown {
    errno: EBUSY,
}
[src/backend/drm/legacy/surface.rs:243] x = Unknown {
    errno: EBUSY,
}
Apr 12 12:56:39.006 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
Apr 12 12:56:39.006 WARN Failed to restart rendering loop. Error: The context has been lost, it needs to be recreated, smithay_module: backend_gbm
Apr 12 12:56:39.069 DEBG Request of type "gone" to close device (13,86), vt: None, seat: seat0, id: 20, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
```

**Comment by Drakulix** [comment]
@vberger Was this fixed by https://github.com/Smithay/smithay/pull/170 or do we still have to adjust the logic to track open drm-devices?

**Comment by vberger** [comment]
Ah no, this is not fixed, #170 was something else I stumbled upon investigating this.
